Algoritmo "exercicio11"
// Desenvolver um programa que triangule uma matriz de ordem 10.
// Deverá aparecer como resposta algo assim na tela:
Var
a, b: inteiro

Inicio

para a de 1 ate 10 passo 1 faca
     para b de 1 ate 10 passo 1 faca
          se (a < 10) entao
             escreva( " ", a, " -", b, " ")
          senao
               escreva( a, " -", b, " ")
          fimse
     fimpara
     escreval() // pular linha
fimpara


Fimalgoritmo